name: area_polygon
description: Calculate the area of a simple 2D polygon given its vertices. A Dart port of the area-polygon npm package.
version: 1.0.0
homepage: https://github.com/adil192/area_polygon
repository: https://github.com/adil192/area_polygon
issue_tracker: https://github.com/adil192/area_polygon/issues

topics:
  - math
  - polygons
  - 2d
  - js-port

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
